### ISSUE TITLE
variable graphics quality settings 

### ISSUE THREAD

**Issue by obviousjim** [CLOUDS-Interactive-Documentary/CLOUDS#54]
We need a way to customize certain graphics quality settings, namely post effects, anti-aliasing levels, and Oculus Rift pixel densities. This will let us take the first step towards scaling CLOUDS to work on a wider variety of machines.

**Comment by OmerShapira** [comment]
Ouch. Not sure it's uniformly possible in every VS...
Would it be possible to add an "LOD" metadata with a number (1,2,3) in the json and filter VS's that can't be loaded on lesser systems?

**Comment by obviousjim** [comment]
The Oculus pixel density and Post Effects are something that we can definitely control globally. In conjunction with #55 + #53 we should be able to handle this.

**Comment by obviousjim** [comment]
Are you down to help w this @OmerShapira :)

**Comment by obviousjim** [comment]
@m1keall1son took care of this one!
