### ISSUE TITLE
CloudsCrypto.h file not found

### ISSUE THREAD

**Issue by edap** [CLOUDS-Interactive-Documentary/CLOUDS#84]
I've clone the OF cloud branch, and clone the CLOUD project inside app, as explained in the readme.Compiling the project with xcode on yosemite, the file CloudVisualSystem.cpp can not found the header CloudsCrypto.h. ,that is also in the .gitignore.

**Comment by obviousjim** [comment]
Hi Davide,

We are still creating a cleaned up version of the project that the public
can compile. Thanks for your interest!

On Wed, Jun 3, 2015 at 1:00 PM, Davide Prati <notifications@github.com>
wrote:

> I've clone the OF cloud branch, and clone the CLOUD project inside app, as
> explained in the readme.Compiling the project with xcode on yosemite, the
> file CloudVisualSystem.cpp can not found the header CloudsCrypto.h. ,that
> is also in the .gitignore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CLOUDS-Interactive-Documentary/CLOUDS/issues/84>.
>



-- 
- James

**Comment by edap** [comment]
ok i close the issue, 
i've just bought the software from vhx, good work!
