### ISSUE TITLE
double declaration of 'i' in DrawnLine::setup

### ISSUE THREAD

**Issue by obviousjim** [CLOUDS-Interactive-Documentary/CLOUDS#96]
@ofZach Found this looking into the crash error:

This seems like it may be broken -- notice i is used for two nested loops

https://github.com/CLOUDS-Interactive-Documentary/CLOUDS/blob/master/CloudsLibrary/src/VisualSystems/DrawnLine/vs_src/drawnLineApp.cpp#L86

I am going to try to fix it but worried it will break other things

**Comment by ofZach** [comment]
can you replace 

for (int i = 0; i < NROT; i++){

with 

for (int k = 0; k < NROT; k++){

**Comment by obviousjim** [comment]
Done! seems to be working great :) if you get a moment I sent you a new binary that I believe fixed the crash error too.
